# Generated by Django 3.1.3 on 2020-12-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countrys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('lead_name', models.CharField(max_length=100)),
                ('young_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='firstcollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('college_nameE', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='firstshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lead_num', models.FloatField()),
                ('young_num', models.FloatField()),
                ('value_num', models.FloatField()),
            ],
        ),
    ]
